name: Build
on:
  push:

env:
  TARGET: minigrep

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            platform: linux-x64
          - os: windows-latest
            platform: windows-x64
          - os: macos-latest
            platform: macos-x64

    runs-on: ${{ matrix.os }}
    steps:
      - name: Fetch repository
        uses: actions/checkout@v2

      - name: Configure rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - name: Enable Cargo caching
        uses: Swatinem/rust-cache@v1

      - name: Build
        run: cargo build --release

      - name: Test
        run: cargo test

      - name: Compress binary executable for Unix
        if: ${{ runner.os == 'macOS' || runner.os == 'Linux' }}
        run: cd ./target/release && tar -cvzf ./../../${{ env.TARGET }}-${{ matrix.platform }}.tar.gz ${{ env.TARGET }}

      - name: Compress binary executable for Windows
        if: ${{ runner.os == 'Windows' }}
        run: cd ./target/release && powershell.exe "compress-archive ${{ env.TARGET }}.exe ./../../${{ env.TARGET }}-${{ matrix.platform }}.zip"

      - name: Upload ${{ matrix.platform }} artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.TARGET }}-${{ matrix.platform }}
          path: ./${{ env.TARGET }}-${{ matrix.platform }}.**